"""add endereco fields to cliente

Revision ID: e76a67f61b8d
Revises: 7ea48bbba3f6
Create Date: 2026-02-26 15:02:33.692881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76a67f61b8d'
down_revision: Union[str, Sequence[str], None] = '7ea48bbba3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('rua', sa.String(length=150), nullable=True))
    op.add_column('clientes', sa.Column('numero', sa.String(length=20), nullable=True))
    op.add_column('clientes', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('clientes', sa.Column('estado', sa.String(length=50), nullable=True))
    op.add_column('clientes', sa.Column('cep', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'cep')
    op.drop_column('clientes', 'estado')
    op.drop_column('clientes', 'cidade')
    op.drop_column('clientes', 'numero')
    op.drop_column('clientes', 'rua')
    # ### end Alembic commands ###
